### ISSUE TITLE
ui-gmap-marker icon attribute set to method causes infinite digest

### ISSUE THREAD

**Issue by silentFred** [angular-ui/angular-google-maps#1262]
Hey there!

Firstly: loving the directives so far. Really grateful for everyone's contribution!

So anyhoo, i'm placing ui-gmap-marker directives inside ui-gmap-google-map and would like them to have different markers based on some condition. So i'm assigning a function to icon to bring back the desired icon url.
```
<ui-gmap-marker
   idKey='specialist.name'
   coords='specialist.pos'
   icon="vm.getCoverPinUrl(specialist.cover)">
</ui-gmap-marker>
```

This throws the following:
```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: function (scope,locals){var value=parsedExpression(scope,locals),result=interceptorFn(value,scope,locals);return isDefined(value)?result:value}; newVal: {\"url\":\"http://cdn1.iconfinder.com/data/icons/orientation-2/32/pin-128.png\"}; oldVal: {\"url\":\"http://cdn1.iconfinder.com/data/icons/orientation-2/32/pin-128.png\"}"],["fn: function (scope,locals){var value=parsedExpression(scope,locals),result=interceptorFn(value,scope,locals);return isDefined(value)?result:value}; newVal: {\"url\":\"http://cdn1.iconfinder.com/data/icons/orientation-2/32/pin-128.png\"}; oldVal: {\"url\":\"http://cdn1.iconfinder.com/data/icons/orientation-2/32/pin-128.png\"}"],["fn: function (scope,locals){var value=parsedExpression(scope,locals),result=interceptorFn(value,scope,locals);return isDefined(value)?result:value}; newVal: {\"url\":\"http://cdn1.iconfinder.com/data/icons/orientation-2/32/pin-128.png\"}; oldVal: {\"url\":\"http://cdn1.iconfinder.com/data/icons/orientation-2/32/pin-128.png\"}"],["fn: function (scope,locals){var value=parsedExpression(scope,locals),result=interceptorFn(value,scope,locals);return isDefined(value)?result:value}; newVal: {\"url\":\"http://cdn1.iconfinder.com/data/icons/orientation-2/32/pin-128.png\"}; oldVal: {\"url\":\"http://cdn1.iconfinder.com/data/icons/orientation-2/32/pin-128.png\"}"],["fn: function (scope,locals){var value=parsedExpression(scope,locals),result=interceptorFn(value,scope,locals);return isDefined(value)?result:value}; newVal: {\"url\":\"http://cdn1.iconfinder.com/data/icons/orientation-2/32/pin-128.png\"}; oldVal: {\"url\":\"http://cdn1.iconfinder.com/data/icons/orientation-2/32/pin-128.png\"}"]]
http://errors.angularjs.org/1.3.0/$rootScope/infdig?p0=10&p1=%5B%5B%22fn%3A%20function%20(scope%2Clocals)%7Bvar%20value%3DparsedExpression(scope%2Clocals)%2Cresult%3DinterceptorFn(value%2Cscope%2Clocals)%3Breturn%20isDefined(value)%3Fresult%3Avalue%7D%3B%20newVal%3A%20%7B%5C%22url%5C%22%3A%5C%22http%3A%2F%2Fcdn1.iconfinder.com%2Fdata%2Ficons%2Forientation-2%2F32%2Fpin-128.png%5C%22%7D%3B%20oldVal%3A%20%7B%5C%22url%5C%22%3A%5C%22http%3A%2F%2Fcdn1.iconfinder.com%2Fdata%2Ficons%2Forientation-2%2F32%2Fpin-128.png%5C%22%7D%22%5D%2C%5B%22fn%3A%20function%20(scope%2Clocals)%7Bvar%20value%3DparsedExpression(scope%2Clocals)%2Cresult%3DinterceptorFn(value%2Cscope%2Clocals)%3Breturn%20isDefined(value)%3Fresult%3Avalue%7D%3B%20newVal%3A%20%7B%5C%22url%5C%22%3A%5C%22http%3A%2F%2Fcdn1.iconfinder.com%2Fdata%2Ficons%2Forientation-2%2F32%2Fpin-128.png%5C%22%7D%3B%20oldVal%3A%20%7B%5C%22url%5C%22%3A%5C%22http%3A%2F%2Fcdn1.iconfinder.com%2Fdata%2Ficons%2Forientation-2%2F32%2Fpin-128.png%5C%22%7D%22%5D%2C%5B%22fn%3A%20function%20(scope%2Clocals)%7Bvar%20value%3DparsedExpression(scope%2Clocals)%2Cresult%3DinterceptorFn(value%2Cscope%2Clocals)%3Breturn%20isDefined(value)%3Fresult%3Avalue%7D%3B%20newVal%3A%20%7B%5C%22url%5C%22%3A%5C%22http%3A%2F%2Fcdn1.iconfinder.com%2Fdata%2Ficons%2Forientation-2%2F32%2Fpin-128.png%5C%22%7D%3B%20oldVal%3A%20%7B%5C%22url%5C%22%3A%5C%22http%3A%2F%2Fcdn1.iconfinder.com%2Fdata%2Ficons%2Forientation-2%2F32%2Fpin-128.png%5C%22%7D%22%5D%2C%5B%22fn%3A%20function%20(scope%2Clocals)%7Bvar%20value%3DparsedExpression(scope%2Clocals)%2Cresult%3DinterceptorFn(value%2Cscope%2Clocals)%3Breturn%20isDefined(value)%3Fresult%3Avalue%7D%3B%20newVal%3A%20%7B%5C%22url%5C%22%3A%5C%22http%3A%2F%2Fcdn1.iconfinder.com%2Fdata%2Ficons%2Forientation-2%2F32%2Fpin-128.png%5C%22%7D%3B%20oldVal%3A%20%7B%5C%22url%5C%22%3A%5C%22http%3A%2F%2Fcdn1.iconfinder.com%2Fdata%2Ficons%2Forientation-2%2F32%2Fpin-128.png%5C%22%7D%22%5D%2C%5B%22fn%3A%20function%20(scope%2Clocals)%7Bvar%20value%3DparsedExpression(scope%2Clocals)%2Cresult%3DinterceptorFn(value%2Cscope%2Clocals)%3Breturn%20isDefined(value)%3Fresult%3Avalue%7D%3B%20newVal%3A%20%7B%5C%22url%5C%22%3A%5C%22http%3A%2F%2Fcdn1.iconfinder.com%2Fdata%2Ficons%2Forientation-2%2F32%2Fpin-128.png%5C%22%7D%3B%20oldVal%3A%20%7B%5C%22url%5C%22%3A%5C%22http%3A%2F%2Fcdn1.iconfinder.com%2Fdata%2Ficons%2Forientation-2%2F32%2Fpin-128.png%5C%22%7D%22%5D%5D
    at http://localhost:3001/discovery-ui/vendor/angular/angular-1.3.0/angular.js:6:959
    at Scope.$get.Scope.$digest (http://localhost:3001/discovery-ui/vendor/angular/angular-1.3.0/angular.js:12:22902)
    at Scope.$get.Scope.$apply (http://localhost:3001/discovery-ui/vendor/angular/angular-1.3.0/angular.js:12:24416)
    at HTMLTableRowElement. (http://localhost:3001/src/client/app/core/directives/rowexpand.directive.js:21:23)
    at HTMLTableRowElement.wrapped (http://localhost:3001/src/client/app/util/raven.js:1251:29)
    at HTMLTableRowElement.n.event.dispatch (http://localhost:3001/discovery-ui/vendor/jquery/1.11.0/jquery-1.11.0.min.js:3:17055)
    at HTMLTableRowElement.n.event.add.r.handle (http://localhost:3001/discovery-ui/vendor/jquery/1.11.0/jquery-1.11.0.min.js:3:13774)
```

Assigning the object directly works well:

```
<ui-gmap-marker
    ng-if="specialist.cover == 'No cover'"
    idKey='specialist.name'
    coords='specialist.pos'
    icon="{url: 'http://www.myiconfinder.com/uploads/iconsets/32-32-e3b0d637d36ffc6a47106a091bb9473d.png'}">
</ui-gmap-marker>
```

Any ideas on what might be causing this? Doing inline conditional expressions produce the same error.

**Comment by nmccready** [comment]
Not sure but if you use the sourcemapp or non minified code it would probably come to light if you walk the code. I currently do not have the time to investigate it.

**Comment by wrummler** [comment]
@silentFred It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it demonstrates the behavior you're asking about.

Closing for now, but will reopen when a running demo of the problem is provided. Thanks.
