### ISSUE TITLE
Polygon with inner holes

### ISSUE THREAD

**Issue by SemihAkar** [angular-ui/angular-google-maps#1337]
In the documentation for 'path' field of 'polygon' directive;

"May be in the form of an array of objects containing latitude and longitude properties, or an array of Google Maps LatLng objects. Alternatively, a GeoJSON Polygon object.

For the case of the GeoJSON Polygon object, only the outer ring (ring index 0) is used to display the polygon. Inner holes (ring indices 1...n) of the Polygon are not displayed."

However, when I put 2 dimensional array into the polygon, it gives the following error;

Error: at index 0: not an instance of LatLng
Error
    at Error (native)
    at new nf (http://maps.gstatic.com/maps-api-v3/api/js/21/1/main.js:24:682)
    at of (http://maps.gstatic.com/maps-api-v3/api/js/21/1/main.js:24:795)
    at http://maps.gstatic.com/maps-api-v3/api/js/21/1/main.js:39:1185
    at jg.forEach (http://maps.gstatic.com/maps-api-v3/api/js/21/1/main.js:29:1641)
    at http://maps.gstatic.com/maps-api-v3/api/js/21/1/main.js:39:1146
    at Oh (http://maps.gstatic.com/maps-api-v3/api/js/21/1/main.js:39:880)
    at Th.setPath (http://maps.gstatic.com/maps-api-v3/api/js/21/1/main.js:39:1514)
    at Th.N.setValues (http://maps.gstatic.com/maps-api-v3/api/js/21/1/main.js:22:84)
    at Th.Sh (http://maps.gstatic.com/maps-api-v3/api/js/21/1/main.js:39:1306)

So I cannot put holes into the polygon, which normally google maps api allows you to do.

**Comment by wrummler** [comment]
> However, when I put 2 dimensional array into the polygon...

This isn't right. The doc you quoted explains what's currently valid for the `path` expression to evaluate to, and 2-dimensional arrays (of anything) aren't valid (yet).

Support for inner rings is apparently on the roadmap, though. See #321.
