### ISSUE TITLE
new dependency (nemLogging, nemLogger -> angular-simple-logger)

### ISSUE THREAD

**Issue by benbentzion** [angular-ui/angular-google-maps#1477]
Hi,

i didn't change anything on my side, and suddenly the map is not working.

i get this error in console - 

Uncaught Error: [$injector:modulerr] Failed to instantiate module airquality due to:
Error: [$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps due to:
Error: [$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.directives.api due to:
Error: [$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.directives.api.models.parent due to:
Error: [$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.directives.api.models.child due to:
Error: [$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.directives.api.utils due to:
Error: [$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.extensions due to:
Error: [$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.providers due to:
Error: [$injector:modulerr] Failed to instantiate module nemLogging due to:
Error: [$injector:nomod] Module 'nemLogging' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.13/$injector/nomod?p0=nemLogging
    at REGEX_STRING_REGEXP (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:63:12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:1767:17
    at ensure (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:1691:38)
    at module (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:1765:14)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4097:22
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=nemLogging&p1=Erro….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.13%2Fangular.js%3A4081%3A5)
    at REGEX_STRING_REGEXP (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:63:12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4120:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=uiGmapgoogle-maps.….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.13%2Fangular.js%3A4081%3A5)
    at REGEX_STRING_REGEXP (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:63:12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4120:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=uiGmapgoogle-maps.….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.13%2Fangular.js%3A4081%3A5)
    at REGEX_STRING_REGEXP (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:63:12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4120:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=uiGmapgoogle-maps.….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.13%2Fangular.js%3A4081%3A5)
    at REGEX_STRING_REGEXP (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:63:12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4120:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=uiGmapgoogle-maps.….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.13%2Fangular.js%3A4081%3A5)
    at REGEX_STRING_REGEXP (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:63:12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4120:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=uiGmapgoogle-maps.….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.13%2Fangular.js%3A4081%3A5)
    at REGEX_STRING_REGEXP (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:63:12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4120:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=uiGmapgoogle-maps.….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.13%2Fangular.js%3A4081%3A5)
    at REGEX_STRING_REGEXP (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:63:12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4120:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=uiGmapgoogle-maps&….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.13%2Fangular.js%3A4081%3A5)
    at REGEX_STRING_REGEXP (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:63:12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4120:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4098:40
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:323:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4081:5)
    at createInjector (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:4007:11)
    at doBootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:1445:20)
    at bootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js:1466:12)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=airquality&p1=Erro…googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.13%2Fangular.js%3A1466%3A12)

please someone can tell me what happened ??

**Comment by nmccready** [comment]
Did u read the error,  and look at the new bower.json and package.json? Your pointing at master them the breaks.

**Comment by nmccready** [comment]
I'll add it to the readme.md for the new dependency and I'll bump the minor to 2.2.X.

**Comment by nmccready** [comment]
Logger can be found here https://github.com/nmccready/angular-simple-logger and it is on npm, and bower.

**Comment by kranthitech** [comment]
+1
