### ISSUE TITLE
TypeError: Cannot read property 'latitude' of undefined  at Object.fn (angular-google-maps.min.js:8)

### ISSUE THREAD

**Issue by nadeemkhan** [angular-ui/angular-google-maps#1658]
TypeError: Cannot read property 'latitude' of undefined
    at Object.fn (angular-google-maps.min.js:8)
    at Scope.$digest (ionic.bundle.js:21349)
    at ionic.bundle.js:21548
    at completeOutstandingRequest (ionic.bundle.js:13322)
    at ionic.bundle.js:13623(anonymous function) @ ionic.bundle.js:18891(anonymous function) @ ionic.bundle.js:16238Scope.$digest @ ionic.bundle.js:21368(anonymous function) @ ionic.bundle.js:21548completeOutstandingRequest @ ionic.bundle.js:13322(anonymous function) @ ionic.bundle.js:13623
2plugins/cordova-plugin-console/www/console-via-logger.js:173 No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.

![screen shot 2015-12-18 at 2 32 05 am](https://cloud.githubusercontent.com/assets/1510017/11881951/d645267a-a52f-11e5-92c8-1d59182fd468.png)

TypeError: Cannot read property 'latitude' of undefined
    at Object.fn (file:///android_asset/www/lib/map/angular-google-maps.min.js:8:2282)
    at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21349:29)
    at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21614:24)
    at HTMLDivElement.<anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:42734:13)
    at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11802:10
    at Array.forEach (native)
    at forEach (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:9312:11)
    at HTMLDivElement.eventHandler (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11801:5)
    at triggerMouseEvent (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2720:7)
    at tapClick (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2709:3)

![screen shot 2015-12-18 at 2 37 50 am](https://cloud.githubusercontent.com/assets/1510017/11882058/5e51f70a-a530-11e5-89dd-a1a223121015.png)

**Comment by cthrax** [comment]
Please formulate a question.
