### ISSUE TITLE
Error using npm install angular-google-maps

### ISSUE THREAD

**Issue by SirPatate** [angular-ui/angular-google-maps#1854]
Hi, I encounter some problems installing angular-google-maps using the command line "npm install angular-google-maps". Can you help me with this issue? 

Here is the bash return error:

```
$ npm install angular-google-maps
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:827:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git resetting remote C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-nmccready-google-maps-utility-library-v3-markerwithlabel-git-b0832bc5 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:827:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:477:12)
npm WARN addRemoteGit  git://github.com/MikaFima/js-rich-marker.git#0383f4bbdad4ddf154772fedbdd27e464600e943 resetting remote C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-MikaFima-js-rich-marker-git-1f09cb2c because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-nmccready-google-maps-utility-library-v3-markerwithlabel-git-b0832bc5: Cloning into bare repository 'C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-nmccready-google-maps-utility-library-v3-markerwithlabel-git-b0832bc5'...
npm ERR! git clone --template=C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-nmccready-google-maps-utility-library-v3-markerwithlabel-git-b0832bc5: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-nmccready-google-maps-utility-library-v3-markerwithlabel-git-b0832bc5: github.com[0: 192.30.252.130]: errno=No error
npm ERR! git clone --template=C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/MikaFima/js-rich-marker.git C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-MikaFima-js-rich-marker-git-1f09cb2c: Cloning into bare repository 'C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-MikaFima-js-rich-marker-git-1f09cb2c'...
npm ERR! git clone --template=C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/MikaFima/js-rich-marker.git C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-MikaFima-js-rich-marker-git-1f09cb2c: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/MikaFima/js-rich-marker.git C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-MikaFima-js-rich-marker-git-1f09cb2c: github.com[0: 192.30.252.130]: errno=No error
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Software\\nodejs\\node.exe" "C:\\Software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular-google-maps"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-nmccready-google-maps-utility-library-v3-markerwithlabel-git-b0832bc5
npm ERR! Cloning into bare repository 'C:\Users\e0000863\AppData\Roaming\npm-cache\_git-remotes\git-github-com-nmccready-google-maps-utility-library-v3-markerwithlabel-git-b0832bc5'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\e0000863\npm-debug.log
```

Could be a problem with npm but i doubt, thx in advance !

**Comment by SirPatate** [comment]
Nothing to do with angular-google-maps, it's a problem of corporate proxy. 

Solved with this command :

```
git config --global url."https://".insteadOf git://

npm config set proxy http://proxyUrl:port
npm config set https-proxy http://proxyUrl:port

git config --global http.proxy http[s]://proxyUrl:port
```

**Comment by davidpelayo** [comment]
@SirPatate, I'm closing therefore this issue.

For the future,

I've added [ISSUE_TEMPLATE.md](https://github.com/angular-ui/angular-google-maps/blob/master/ISSUE_TEMPLATE.md) so there explains how to report a potential bug better.

Please provide detailed info, as per the ISSUE_TEMPLATE, including jsbins/plunkr/jsfiddle in order to help you better.

Thanks.
