### ISSUE TITLE
Google Map implementation getting this error  ##ctorParameters.map is not a function

### ISSUE THREAD

**Issue by jagdishparmar** [angular-ui/angular-google-maps#2016]
Error: TypeError: ctorParameters.map is not a function
   at ReflectionCapabilities.parameters (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:2118:51)
   at Reflector.parameters (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:2319:52)
   at CompileMetadataResolver.getDependenciesMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14336:81)
   at CompileMetadataResolver.getTypeMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14301:28)
   at CompileMetadataResolver.getProviderMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14496:42)
   at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14444:47)
   at Array.forEach (<anonymous>)
   at CompileMetadataResolver.getProvidersMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14428:21)
   at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14120:73)
   at Array.forEach (<anonymous>)
Evaluating http://localhost:3000/app/main.js
Error loading http://localhost:3000/app/main.js
(anonymous) @ localhost/:31
ZoneDelegate.invoke @ zone.js:232
Zone.run @ zone.js:114
(anonymous) @ zone.js:502
ZoneDelegate.invokeTask @ zone.js:265
Zone.runTask @ zone.js:154
drainMicroTaskQueue @ zone.js:401
ZoneTask.invoke @ zone.js:339
systemjs.config.js:73 TypeError: ctorParameters.map is not a function
   at ReflectionCapabilities.parameters (core.umd.js:2118)
   at Reflector.parameters (core.umd.js:2319)
   at CompileMetadataResolver.getDependenciesMetadata (compiler.umd.js:14336)
   at CompileMetadataResolver.getTypeMetadata (compiler.umd.js:14301)
   at CompileMetadataResolver.getProviderMetadata (compiler.umd.js:14496)
   at eval (compiler.umd.js:14444)
   at Array.forEach (<anonymous>)
   at CompileMetadataResolver.getProvidersMetadata (compiler.umd.js:14428)
   at eval (compiler.umd.js:14120)
   at Array.forEach (<anonymous>)
(anonymous) @ systemjs.config.js:73
Chirag • 5 mins

**Comment by ninoyaghoubi** [comment]
mote the thread

**Comment by ninoyaghoubi** [comment]
mute the thread
